var QUOTES={zh:[
{text:'生活不止眼前的苟且，还有诗和远方。',author:'高晓松'},
{text:'世界以痛吻我，要我报之以歌。',author:'泰戈尔'},
{text:'人生如逆旅，我亦是行人。',author:'苏轼'},
{text:'但凡不能杀死你的，最终都会使你更强大。',author:'尼采'},
{text:'黑夜无论怎样悠长，白昼总会到来。',author:'莎士比亚'},
{text:'宝剑锋从磨砺出，梅花香自苦寒来。',author:'佚名'},
{text:'千里之行，始于足下。',author:'老子'},
{text:'天行健，君子以自强不息。',author:'《周易》'},
{text:'路漫漫其修远兮，吾将上下而求索。',author:'屈原'},
{text:'既然选择了远方，便只顾风雨兼程。',author:'汪国真'},
{text:'不经一番寒彻骨，怎得梅花扑鼻香。',author:'黄檗禅师'},
{text:'人无远虑，必有近忧。',author:'《论语》'},
{text:'己所不欲，勿施于人。',author:'《论语》'},
{text:'学而不思则罔，思而不学则殆。',author:'《论语》'},
{text:'三人行，必有我师焉。',author:'《论语》'},
{text:'知之为知之，不知为不知，是知也。',author:'《论语》'},
{text:'君子坦荡荡，小人长戚戚。',author:'《论语》'},
{text:'岁寒，然后知松柏之后凋也。',author:'《论语》'},
{text:'吾生也有涯，而知也无涯。',author:'《庄子》'},
{text:'相濡以沫，不如相忘于江湖。',author:'《庄子》'},
{text:'大鹏一日同风起，扶摇直上九万里。',author:'李白'},
{text:'天生我材必有用，千金散尽还复来。',author:'李白'},
{text:'长风破浪会有时，直挂云帆济沧海。',author:'李白'},
{text:'会当凌绝顶，一览众山小。',author:'杜甫'},
{text:'读书破万卷，下笔如有神。',author:'杜甫'},
{text:'海内存知己，天涯若比邻。',author:'王勃'},
{text:'老骥伏枥，志在千里。',author:'曹操'},
{text:'非淡泊无以明志，非宁静无以致远。',author:'诸葛亮'},
{text:'先天下之忧而忧，后天下之乐而乐。',author:'范仲淹'},
{text:'人生自古谁无死，留取丹心照汗青。',author:'文天祥'},
{text:'路遥知马力，日久见人心。',author:'《增广贤文》'},
{text:'一年之计在于春，一日之计在于晨。',author:'《增广贤文》'},
{text:'有意栽花花不发，无心插柳柳成阴。',author:'《增广贤文》'},
{text:'知己知彼，将心比心。',author:'《增广贤文》'},
{text:'近水楼台先得月，向阳花木早逢春。',author:'《增广贤文》'},
{text:'少壮不努力，老大徒伤悲。',author:'《乐府诗集》'},
{text:'塞翁失马，焉知非福。',author:'《淮南子》'},
{text:'忠言逆耳利于行，良药苦口利于病。',author:'《孔子家语》'},
{text:'人不可貌相，海水不可斗量。',author:'中国谚语'},
{text:'山重水复疑无路，柳暗花明又一村。',author:'陆游'},
{text:'纸上得来终觉浅，绝知此事要躬行。',author:'陆游'},
{text:'横看成岭侧成峰，远近高低各不同。',author:'苏轼'},
{text:'但愿人长久，千里共婵娟。',author:'苏轼'},
{text:'宠辱不惊，看庭前花开花落。',author:'《菜根谭》'},
{text:'不以物喜，不以己悲。',author:'范仲淹'},
{text:'穷则独善其身，达则兼济天下。',author:'《孟子》'},
{text:'锲而不舍，金石可镂。',author:'《荀子》'},
{text:'博观而约取，厚积而薄发。',author:'苏轼'},
],en:[
{text:'The only way to do great work is to love what you do.',author:'Steve Jobs'},
{text:'Stay hungry, stay foolish.',author:'Steve Jobs'},
{text:'The best time to plant a tree was 20 years ago. The second best time is now.',author:'Chinese Proverb'},
{text:'In the middle of difficulty lies opportunity.',author:'Albert Einstein'},
{text:'Imagination is more important than knowledge.',author:'Albert Einstein'},
{text:'Be the change that you wish to see in the world.',author:'Mahatma Gandhi'},
{text:'Life is what happens when you\'re busy making other plans.',author:'John Lennon'},
{text:'Get busy living or get busy dying.',author:'Stephen King'},
{text:'Everything you\'ve ever wanted is on the other side of fear.',author:'George Addair'},
{text:'Absence makes the heart grow fonder.',author:'English proverb'},
{text:'Actions speak louder than words.',author:'English proverb'},
{text:'All that glitters is not gold.',author:'William Shakespeare'},
{text:'A bird in the hand is worth two in the bush.',author:'John Bunyan'},
{text:'Blood is thicker than water.',author:'English proverb'},
{text:'A chain is only as strong as its weakest link.',author:'Thomas Reid'},
{text:'Charity begins at home.',author:'English proverb'},
{text:'Curiosity killed the cat.',author:'English proverb'},
{text:'Don\'t count your chickens before they\'re hatched.',author:'English proverb'},
{text:'Don\'t judge a book by its cover.',author:'English proverb'},
{text:'Don\'t put all your eggs in one basket.',author:'English proverb'},
{text:'Early to bed and early to rise, makes a man healthy, wealthy and wise.',author:'Benjamin Franklin'},
{text:'Every cloud has a silver lining.',author:'English proverb'},
{text:'Fortune favors the brave.',author:'English proverb'},
{text:'A friend in need is a friend indeed.',author:'English proverb'},
{text:'Genius is one percent inspiration and ninety-nine percent perspiration.',author:'Thomas Edison'},
{text:'Knowledge is power.',author:'Francis Bacon'},
{text:'No man is an island.',author:'John Donne'},
{text:'Practice makes perfect.',author:'English proverb'},
{text:'Rome was not built in a day.',author:'English proverb'},
{text:'When in Rome, do as the Romans do.',author:'English proverb'},
],ja:[
{text:'千里の道も一歩から。',author:'老子'},
{text:'為せば成る、為さねば成らぬ何事も。',author:'上杉鷹山'},
{text:'石の上にも三年。',author:'日本のことわざ'},
{text:'七転び八起き。',author:'日本のことわざ'},
{text:'一期一会。',author:'千利休'},
{text:'継続は力なり。',author:'日本のことわざ'},
{text:'明日は明日の風が吹く。',author:'日本のことわざ'},
{text:'案ずるより産むが易し。',author:'日本のことわざ'},
{text:'塵も積もれば山となる。',author:'日本のことわざ'},
{text:'急がば回れ。',author:'日本のことわざ'},
{text:'花鳥風月。',author:'日本の美意識'},
{text:'初心忘るべからず。',author:'世阿弥'},
{text:'一石二鳥。',author:'日本の諺'},
{text:'井の中の蛙大海を知らず。',author:'日本の諺'},
{text:'猿も木から落ちる。',author:'日本の諺'},
{text:'三人寄れば文殊の知恵。',author:'日本の諺'},
{text:'二兎を追う者は一兎をも得ず。',author:'日本の諺'},
{text:'雨垂れ石を穿つ。',author:'日本の諺'},
{text:'言うは易く行なうは難し。',author:'日本の諺'},
{text:'犬も歩けば棒に当たる。',author:'日本の諺'},
{text:'馬の耳に念仏。',author:'日本の諺'},
{text:'鬼に金棒。',author:'日本の諺'},
{text:'可愛い子には旅をさせよ。',author:'日本の諺'},
{text:'聞くは一時の恥聞かぬは一生の恥。',author:'日本の諺'},
{text:'口は災いの元。',author:'日本の諺'},
{text:'郷に入っては郷に従え。',author:'日本の諺'},
{text:'転ばぬ先の杖。',author:'日本の諺'},
{text:'備えあれば憂いなし。',author:'日本の諺'},
{text:'立つ鳥跡を濁さず。',author:'日本の諺'},
{text:'出る杭は打たれる。',author:'日本の諺'},
{text:'鉄は熱いうちに打て。',author:'日本の諺'},
{text:'灯台下暗し。',author:'日本の諺'},
{text:'能ある鷹は爪を隠す。',author:'日本の諺'},
{text:'笑う門には福来る。',author:'日本の諺'},
]};
